import type { Metadata } from 'next';
import { notFound } from 'next/navigation';
import pages from '@/lib/content.json';
import { ContactBand } from '@/components/site-shell';
import { InquiryForm } from '@/components/inquiry-form';
export function generateStaticParams(){return pages.filter(p=>p.path!=='/').map(p=>({slug:p.path.slice(1).split('/')}))}
async function getPage(params:Promise<{slug:string[]}>){const {slug}=await params;return pages.find(p=>p.path==='/'+slug.join('/'))}
export async function generateMetadata({params}:{params:Promise<{slug:string[]}>}):Promise<Metadata>{const page=await getPage(params);return {title:page?.title,alternates:{canonical:'https://burari-net.jp'+(page?.path||'')+'/'}}}
const english:Record<string,string>={'/businessguide':'OUR BUSINESS','/company':'COMPANY','/recruitment':'RECRUIT','/agency':'PARTNERSHIP','/contact':'CONTACT','/privacy':'PRIVACY POLICY','/sitemap':'SITE MAP','/businessguide/power_consulting':'POWER CONSULTING','/businessguide/led':'LED LIGHTING','/businessguide/specialcontents':'HOW IT WORKS'};
export default async function ContentPage({params}:{params:Promise<{slug:string[]}>}){const page=await getPage(params);if(!page)notFound();return <main id="main"><section className="page-hero"><div className="breadcrumb"><a href="/">HOME</a><span>/</span>{page.title}</div><span className="eyebrow">{english[page.path]}</span><h1>{page.title}</h1></section><div className={'page-layout '+(page.path==='/company'?'company-layout':'')}><aside className="page-aside"><span className="eyebrow">BURARI NET</span><nav aria-label="関連ページ">{pages.filter(p=>p.path!=='/'&&p.path!=='/privacy'&&p.path!=='/sitemap').map(p=><a key={p.path} href={p.path+'/'} aria-current={p.path===page.path?'page':undefined}>{p.title}<span>↗</span></a>)}</nav><a className="aside-simulator" href="/#simulator">コスト削減<br/>シミュレーター <span>→</span></a></aside><article className={'page-content '+(page.path==='/company'?'company-content':'')+(page.path.includes('specialcontents')?' slides-content':'')}><div className="prose" dangerouslySetInnerHTML={{__html:page.html}}/>{page.fields.length>0&&<InquiryForm name={page.path.slice(1)} fields={page.fields}/>}</article></div><ContactBand/></main>}
