'use client';
import { useState } from 'react';
import { ArrowUpRight, Calculator, ArrowRight } from 'lucide-react';
import { Choice } from './choice';
import { calculate, companies } from '@/lib/simulator.mjs';
const initial={ev:'',floor:'',format:'',pump:'',pump_power:'',parking:'',contractpower:'',factor:'',power_company:'6'};
const yesno:[string,string][]=[['1','あり'],['2','なし']];
const format=(v:number)=>new Intl.NumberFormat('ja-JP').format(v);
export function Simulator(){
 const [values,setValues]=useState(initial);
 const [result,setResult]=useState<ReturnType<typeof calculate>|null>(null);
 function update(key:keyof typeof initial,value:string){setValues(old=>({...old,[key]:value,...(key==='pump'&&value!=='1'?{pump_power:''}:{}),...(key==='ev'&&value!=='1'?{floor:'',format:''}:{})}));setResult(null)}
 const field=(key:keyof typeof initial,label:string,items:[string,string][],disabled=false)=><Choice name={key} label={label} value={values[key]} items={items} disabled={disabled} onChange={value=>update(key,value)}/>;
 return <div className="simulator"><form className="sim-input" onSubmit={e=>{e.preventDefault();setResult(calculate(values))}}><fieldset><legend><span>01</span> 設備の情報</legend><div className="field-grid">{field('ev','エレベーター',yesno)}{field('parking','立体駐車場',yesno)}{field('floor','エレベーターの階層',[['2','〜9階'],['3','10階〜']],values.ev!=='1')}{field('format','エレベーターの形式',[['1','ロープ式'],['2','油圧式']],values.ev!=='1')}{field('pump','給水ポンプ',yesno)}{field('pump_power','モーターの大きさ',['1.5','2.2','3.6','5.5'].map(v=>[v,v+' kW']),values.pump!=='1')}</div></fieldset><fieldset><legend><span>02</span> ご契約の情報</legend><div className="field-grid">{field('contractpower','現在の契約電力',Array.from({length:26},(_,i)=>[String(i+5),(i+5)+' kW']))}{field('factor','力率',[['1','80%'],['2','85%'],['3','90%']])}<div className="wide-field">{field('power_company','管轄電力会社',companies.map((c:string,i:number)=>[String(i+1),c]))}</div></div></fieldset><button type="submit" className="button dark-button">削減額をシミュレーション <ArrowRight size={18}/></button></form><div className="sim-result" aria-live="polite" aria-atomic="true"><span className="eyebrow">ESTIMATED SAVINGS</span><h3>コスト削減の試算結果</h3>{!result?<div className="result-empty"><Calculator size={38} strokeWidth={1}/><p>設備とご契約の情報を選択して<br/>削減額をシミュレーション。</p><span>月間・年間の削減額を表示します。</span></div>:result.error?<div className="result-error" role="alert"><p>{result.error}</p><a href="tel:0787710382">078-771-0382 <ArrowUpRight size={16}/></a></div>:<><p className="result-label">年間{result.year!>0?'の削減見込額':'の差額'}</p><p className="result-amount">{format(result.year!)}<small>円</small></p><p className="result-month">月間 <strong>{format(result.month!)} 円</strong></p><div className="result-comparison"><div><span>改善前</span><strong>{format(result.beforePrice!)} 円</strong><small>{result.beforePower} kW</small></div><ArrowRight size={18}/><div><span>改善後</span><strong>{format(result.afterPrice!)} 円</strong><small>{result.afterPower} kW</small></div></div>{result.year!<=0&&<p className="result-warning">この条件では削減が見込めません。詳しくはお問い合わせください。</p>}</>}<div className="sim-note"><p>※計測後の数値とは異なる場合がございます。</p><p>既存サイト掲載の単価に基づく参考試算です。現在の電気料金を保証するものではありません。導入費用は含みません。</p><a href="/businessguide/specialcontents/">コスト削減のしくみ <ArrowUpRight size={15}/></a></div></div></div>
}
