import { ArrowDown, ArrowUpRight, ArrowRight } from 'lucide-react';
import { ContactBand } from '@/components/site-shell';
import { Simulator } from '@/components/simulator';
export const metadata={alternates:{canonical:'https://burari-net.jp/'}};
export default function Home(){return <main id="main">
<section className="hero"><div className="hero-copy"><span className="eyebrow"><span className="status-dot"/> ENERGY & ENVIRONMENT</span><h1>コスト削減と、<br/>気持ちの良い<br/><span>地球環境を。</span></h1><p>省エネ・電力コスト削減などを<br/>トータル的にご提案・施工・管理。</p><a className="button lime-button" href="/businessguide/">事業案内を見る <ArrowUpRight size={20}/></a><a className="hero-scroll" href="#greeting"><ArrowDown size={15}/> SCROLL TO EXPLORE</a></div><div className="hero-photo"><div className="photo-caption"><span>BURARI NET</span><p>「エネルギー」と向き合う。</p></div></div></section>
<a className="simulator-ribbon" href="#simulator"><span className="ribbon-tag">SIMULATION</span><span>電気基本料金、どれくらい削減できる？<small>コスト削減シミュレーター</small></span><span className="round-arrow"><ArrowDown size={23}/></span></a>
<section id="greeting" className="section greeting"><div><span className="eyebrow">01 — GREETING</span><h2>ご挨拶</h2></div><div><p className="greeting-lead">昨今の電力事情により、節電・省エネの重要性が高まり、「エネルギー」と向き合うことが当たり前の時代となりました。</p><p>株式会社ぶらりネットは、</p><p>お客様に省エネ・電力コスト削減などをトータル的にご提案・施工・管理を行い支援していきます。</p><p>そして、コスト削減と同時に、気持ちの良い地球環境を作ることに貢献してまいります。</p></div></section>
<section className="section business-section"><div className="section-heading"><div><span className="eyebrow">02 — OUR BUSINESS</span><h2>主な事業</h2></div><a className="text-link" href="/businessguide/">事業案内 <ArrowUpRight size={18}/></a></div><div className="business-grid">{businesses.map((b,i)=><article className="business-card" key={b.title}><div className="business-image"><img src={b.image} alt={b.title} loading="lazy"/></div><div className="business-body"><span className="card-index">0{i+1}</span><h3>{b.title}</h3><p>{b.text}</p>{b.href&&<a href={b.href} className="card-link" aria-label={b.title+'について詳しく見る'}>詳しく見る <ArrowRight size={18}/></a>}</div></article>)}</div></section>
<section id="simulator" className="section"><span className="eyebrow">03 — SIMULATION</span><h2>コスト削減シミュレーター</h2><p className="section-intro">エレベーター・給水ポンプなどの設備と、ご契約の情報から試算できます。</p><Simulator/></section>
<section className="original-visuals section"><div className="section-heading"><div><span className="eyebrow">BURARI NET</span><h2>省エネ・電力コスト削減</h2></div></div><div className="visual-gallery"><img src="/application/files/2814/3802/7965/burari_slide_03.jpg" alt="電気代、払い過ぎていませんか？ 基本料金から50%以上削減できる可能性があります" loading="lazy"/><img src="/application/files/2114/3802/6247/burari_slide_02.jpg" alt="株式会社ぶらりネットは省エネ・電力コスト削減を支援します" loading="lazy"/><img src="/application/files/8614/3802/6248/burari_slide_01.jpg" alt="省エネ・環境に向けたぶらりネットの取り組み" loading="lazy"/></div></section>
<section className="section notice-section"><div className="notice"><h2>ご注意下さい！！</h2><p>最近、一部の悪質な業者が当社や電力会社を装い、 電子ブレーカーの販売と称した強引な営業を行っているとの情報が寄せられています。<br/>しかし、当社及び当社関連企業はこのような悪質な販売勧奨は一切行っておりません。 お客様におかれましても、十分にご注意ください。<br/>また、万一こうした手口にあわれました場合には、当社までお問い合わせのうえ、ご相談ください。</p></div><div className="company-links"><a href="/company/">企業情報 <span>↗</span></a><a href="/agency/">代理店・販売パートナー募集 <span>↗</span></a><a href="/recruitment/">採用情報 <span>↗</span></a></div></section><ContactBand/></main>}
const businesses=[
{title:'電力コンサルティング',image:'/application/files/5014/3802/6248/burari_img_03.jpg',text:'電子ブレーカーを導入し電力会社との契約を変更することで、 電気基本料金の大幅な削減を可能にします。',href:'/businessguide/power_consulting/'},
{title:'LED省エネ照明機器',image:'/application/files/1714/3802/6249/burari_img_04.jpg',text:'照明をLEDにすることで省エネ・電力コスト削減に繋がります。当社では、お客様の要望を考慮し適切な照明のご提案から施工までを自社で行っています。',href:'/businessguide/led/'},
{title:'ホームページ制作',image:'/application/files/3814/3802/6247/burari_img_19.jpg',text:'ECサイトの運営などのノウハウを蓄積しているプログラマー・デザイナーにより、多業種・多業態の商品やサービスに対応出来るＷＥＢサイトをお作りいたします。'},
{title:'海外流通事業',image:'/application/files/8814/3802/6249/burari_img_05.jpg',text:'事務用品や店舗装飾品など各企業様で運営に必要とされる消耗品を「必要な時に必要なだけ、より安く」提供する、 卸売業として事業を行っています。 意外と気づかなかったコスト削減をご提案致します。'},
{title:'環境・省エネ製品',image:'/application/files/8714/3802/6246/burari_img_06.jpg',text:'省電力空調・太陽光発電装置・蓄電池の他、電気の「見える化」や自動的にエネルギーの最適化を行う「制御装置」をご提案いたします。'},
{title:'エコプリンター レンタル事業',image:'/application/files/3814/3802/6248/burari_img_20.jpg',text:'月額定額にてお客様にプリンタをご提供し、さらにインク代は完全無料でご利用できる、 カラープリントし放題のサービスです。'}];
